name: Deploy .output to dist

on:
  push:
    branches:
      - master  # メインブランチが変更されたときにトリガー

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Deploy .output to dist branch
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          # distブランチをチェックアウトし、存在しない場合は作成
          git checkout -B dist
          # 一度すべてを削除し、.outputのみを残す (.git, .outputを除外)
          find . -mindepth 1 -not -path './.git' -not -path './.git/*' -not -path './.output*' | xargs rm -rf
          # 全変更をステージに追加（削除も含む）
          git add -A
          git commit -m "Deploy .output to dist branch"
          # distブランチにpush
          git push -f https://${GH_PAT}@github.com/tekalu1/api-automator.git dist
